name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        git clone https://github.com/sealstore/sealbuild.git build
        cd build
        export GO111MODULE=on && export GOPROXY=https://goproxy.io && export GOOS=linux && export GOARCH=amd64 && go build -o ../sealbuild -v && chmod a+x ../sealbuild
        cd ../ && ./sealbuild -f config.ini -t config
        ls -l
        cat /tmp/kuboard/config

    - uses: actions/upload-artifact@master
      with:
        name: kuboard
        path: /tmp/kuboard/
